/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 13 22:09:50 GMT 2024
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.parser.ParseError;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParseError_ESTest extends ParseError_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParseError parseError0 = new ParseError(1, "yWOcO#b=)*~2t)W@");
      String string0 = parseError0.toString();
      assertEquals("1: yWOcO#b=)*~2t)W@", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object[] objectArray0 = new Object[9];
      ParseError parseError0 = new ParseError(311, "w\"Xgj.s", objectArray0);
      assertEquals(311, parseError0.getPosition());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ParseError parseError0 = new ParseError(1, "yWOcO#b=)*~2t)W@");
      parseError0.getErrorMessage();
      assertEquals(1, parseError0.getPosition());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParseError parseError0 = new ParseError(1, "yWOcO#b=)*~2t)W@");
      int int0 = parseError0.getPosition();
      assertEquals(1, int0);
  }
}
