/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 13 22:23:12 GMT 2024
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.OutputStreamWriter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.jsoup.nodes.Attribute;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.Document;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Attribute_ESTest extends Attribute_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Attribute attribute0 = Attribute.createFromEncoded("tc^4It6>(@", "I!kGO\"N@Xfk");
      attribute0.hashCode();
      assertEquals("tc^4It6>(@", attribute0.getKey());
      assertEquals("I!kGO\"N@Xfk", attribute0.getValue());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Attribute attribute0 = new Attribute("Z65dR|bRRS@DRzv", (String) null);
      attribute0.hashCode();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Attribute attribute0 = new Attribute("Z65dR|bRRS@DRzv", (String) null);
      Attribute attribute1 = new Attribute("Z65dR|bRRS@DRzv", "Z65dR|bRRS@DRzv");
      boolean boolean0 = attribute0.equals(attribute1);
      //  // Unstable assertion: assertTrue(attribute1.equals((Object)attribute0));
      //  // Unstable assertion: assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Attribute attribute0 = new Attribute("Z65dR|bRRS@DRzv", (String) null);
      Attribute attribute1 = attribute0.clone();
      boolean boolean0 = attribute0.equals(attribute1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Attribute attribute0 = Attribute.createFromEncoded("tc^4It6>(@", "I!kGO\"N@Xfk");
      Attribute attribute1 = new Attribute("I!kGO\"N@Xfk", "tc^4It6>(@");
      boolean boolean0 = attribute0.equals(attribute1);
      assertFalse(boolean0);
      assertEquals("I!kGO\"N@Xfk", attribute0.getValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Attribute attribute0 = Attribute.createFromEncoded(".kH.qw", "Qf<I");
      boolean boolean0 = attribute0.equals("Qf<I");
      assertEquals("Qf<I", attribute0.getValue());
      assertEquals(".kH.qw", attribute0.getKey());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attribute attribute0 = new Attribute("m(%)sBcPOrz@uek$LM", "Ds~P!YSLX'", attributes0);
      boolean boolean0 = attribute0.equals((Object) null);
      assertEquals("Ds~P!YSLX'", attribute0.getValue());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attribute attribute0 = new Attribute("itemscope", "itemscope", attributes0);
      Attribute attribute1 = new Attribute("itemscope", "muted");
      boolean boolean0 = attribute0.equals(attribute1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Attribute attribute0 = new Attribute("R#5kSr]o|_q#P", (String) null);
      boolean boolean0 = attribute0.isBooleanAttribute();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Attribute attribute0 = new Attribute("7<", "");
      boolean boolean0 = attribute0.isBooleanAttribute();
      assertEquals("", attribute0.getValue());
      assertEquals("7<", attribute0.getKey());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attribute attribute0 = new Attribute("itemscope", "itemscope", attributes0);
      boolean boolean0 = attribute0.isBooleanAttribute();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attribute attribute0 = new Attribute("Z65dR|bRR@DRzv", "", attributes0);
      String string0 = attribute0.html();
      assertEquals("Z65dR|bRR@DRzv=\"\"", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MockFile mockFile0 = new MockFile("6&;b~tIUlH\"? +S$x=", "");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      OutputStreamWriter outputStreamWriter0 = new OutputStreamWriter(mockPrintStream0);
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      Attribute.html("q?< (<2dR\"V(1", (String) null, (Appendable) outputStreamWriter0, document_OutputSettings0);
      assertEquals(Document.OutputSettings.Syntax.html, document_OutputSettings0.syntax());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      Document.OutputSettings.Syntax document_OutputSettings_Syntax0 = Document.OutputSettings.Syntax.xml;
      document_OutputSettings0.syntax(document_OutputSettings_Syntax0);
      boolean boolean0 = Attribute.shouldCollapseAttribute("muted", "K%ASn*i", document_OutputSettings0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      boolean boolean0 = Attribute.isDataAttribute("data-'J=\"UF~ H\"");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      boolean boolean0 = Attribute.isDataAttribute("data-");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attribute attribute0 = new Attribute("Z65dR|bRR@DRzv", "", attributes0);
      assertEquals("", attribute0.getValue());
      
      attribute0.setValue("");
      assertEquals("Z65dR|bRR@DRzv", attribute0.getKey());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attribute attribute0 = Attribute.createFromEncoded("~1709i_C:8/EF%sjd", ");Hbw`&\"_m{AU!");
      attributes0.put(attribute0);
      attribute0.setValue("readonly");
      assertEquals("readonly", attribute0.getValue());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.put("readonly", "readonly");
      Attribute attribute0 = Attribute.createFromEncoded("~1709i_C:8/EF%sjd", ");Hbw`&\"_m{AU!");
      attributes1.put(attribute0);
      assertEquals("~1709i_C:8/EF%sjd", attribute0.getKey());
      
      String[] stringArray0 = new String[2];
      attributes1.keys = stringArray0;
      attribute0.setKey("readonly");
      assertEquals(");Hbw`&\"_m{AU!", attribute0.getValue());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Attribute attribute0 = new Attribute("M|.D", "org.jsoup.nodes.Attribute");
      Attributes attributes0 = new Attributes();
      attributes0.put(attribute0);
      assertEquals("M|.D", attribute0.getKey());
      
      attribute0.setKey("org.jsoup.nodes.Attribute");
      assertEquals("org.jsoup.nodes.Attribute", attribute0.getValue());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Attribute attribute0 = Attribute.createFromEncoded("oDl=,TEuu4xt^,", "oDl=,TEuu4xt^,");
      attribute0.setKey("oDl=,TEuu4xt^,");
      assertEquals("oDl=,TEuu4xt^,", attribute0.getValue());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Attribute attribute0 = Attribute.createFromEncoded("6.SA,dM9", "6.SA,dM9");
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      boolean boolean0 = attribute0.shouldCollapseAttribute(document_OutputSettings0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Attribute attribute0 = Attribute.createFromEncoded(".kH.qw", "Qf<I");
      String string0 = attribute0.toString();
      assertEquals(".kH.qw=\"Qf<I\"", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Attribute attribute0 = new Attribute("M|.D", "org.jsoup.nodes.Attribute");
      boolean boolean0 = attribute0.isDataAttribute();
      assertEquals("M|.D", attribute0.getKey());
      assertFalse(boolean0);
      assertEquals("org.jsoup.nodes.Attribute", attribute0.getValue());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Attribute attribute0 = new Attribute("noresize", "noresize");
      attribute0.html();
  }
}
