/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 13 22:21:39 GMT 2024
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.DataNode;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DataNode_ESTest extends DataNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DataNode dataNode0 = DataNode.createFromEncoded("'; t~jbAa", "org.jsoup.nodes.Node$OuterHtmlVisitor");
      assertFalse(dataNode0.hasParent());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DataNode dataNode0 = new DataNode("Wt~w5rhqh`HZky", "Wj5$@Yu?R");
      DataNode dataNode1 = dataNode0.setWholeData("Wt~w5rhqh`HZky");
      assertEquals("#data", dataNode1.nodeName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DataNode dataNode0 = new DataNode(">+2`v|%cOXr/y&v", ">+2`v|%cOXr/y&v");
      dataNode0.toString();
  }
}
