/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 13 22:18:34 GMT 2024
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attribute;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.XmlDeclaration;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XmlDeclaration_ESTest extends XmlDeclaration_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("=fDn#c", "=fDn#c", true);
      Attributes attributes0 = xmlDeclaration0.attributes();
      Attribute attribute0 = Attribute.createFromEncoded("<", "qy5ng9!f`v@l\"");
      attributes0.put(attribute0);
      String string0 = xmlDeclaration0.toString();
      assertEquals("<!=fDn#c <=\"qy5ng9!f`v@l&quot;\"!>", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("909", "909", true);
      String string0 = xmlDeclaration0.getWholeDeclaration();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("", "", false);
      assertEquals("#declaration", xmlDeclaration0.nodeName());
      
      String string0 = xmlDeclaration0.toString();
      assertEquals("<??>", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("", true);
      xmlDeclaration0.name();
      assertEquals("#declaration", xmlDeclaration0.nodeName());
  }
}
