/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 13 22:37:24 GMT 2024
 */

package org.jsoup;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.jsoup.HttpStatusException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HttpStatusException_ESTest extends HttpStatusException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException(". Status=", 1, "^.B&12");
      MockThrowable mockThrowable0 = new MockThrowable(httpStatusException0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException("", 0, "");
      int int0 = httpStatusException0.getStatusCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException(". Status=", 1, "^.B&12");
      String string0 = httpStatusException0.getUrl();
      assertEquals("^.B&12", string0);
  }
}
